workflows:
  unity-ios-workflow:
    name: Unity iOS Build

    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Build info
        script: echo "Starting Unity iOS build"

    artifacts:
      - build/**/*